FROM denoland/deno:debian

USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates curl git libc6-dev nodejs unzip xz-utils \
  && rm -rf /var/lib/apt/lists/*

ENV MOON_IGNORE_PREBUILD=1
ENV MOON_NO_WORKSPACE=1

WORKDIR /workspace
